### ISSUE TITLE
翻译报错，无法使用。

### ISSUE THREAD

**Issue by Langeeker** [akl7777777/bob-plugin-akl-cnki-free-translate#2]
请求错误。

**Comment by akl7777777** [comment]
![image](https://github.com/akl7777777/bob-plugin-akl-cnki-free-translate/assets/84266551/901a615f-e4ed-4211-ba9e-e44f23fc3c71)
我刚刚试过了没问题啊,你是不是字符太长了,一般这种翻译都有一个最长限制
